import Head from "next/head";
import Geolocation from '../components/Geolocation';

export default function Home() {

  

  return (
    <div>
      <Head>
        <title>Devansh Khullar | Web Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Geolocation/>
      
      
    </div>
  );
}

